#!/usr/bin/env bash
# Milestone D1: reproducible local/A800 environments and real sibling installs.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MODE="${1:-cpu-test}"

require_python_312() {
  local python_bin="$1"
  if ! "${python_bin}" -c 'import sys; raise SystemExit(sys.version_info[:2] != (3, 12))'; then
    echo "error: ${python_bin} must be Python 3.12" >&2
    exit 2
  fi
}

install_source_path_file() {
  local venv_dir="$1"
  local site_packages
  site_packages="$("${venv_dir}/bin/python" -c 'import site; print(site.getsitepackages()[0])')"
  # Keep a non-hidden .pth file because some Python 3.12 builds skip the
  # underscore-prefixed files generated by editable installs.
  printf '%s\n%s\n%s\n' \
    "${ROOT_DIR}" \
    "${ROOT_DIR}/tau2-bench/src" \
    "${ROOT_DIR}/verl" \
    > "${site_packages}/tau3_grpo_local_sources.pth"
}

case "${MODE}" in
  a800-qwen35)
    exec bash "${ROOT_DIR}/env_info/setup_qwen35.sh"
    ;;
  cpu-test)
    PYTHON_BIN="${PYTHON_BIN:-python3.12}"
    require_python_312 "${PYTHON_BIN}"
    VENV_DIR="${ROOT_DIR}/.venv-cpu"
    "${PYTHON_BIN}" -m venv "${VENV_DIR}"
    "${VENV_DIR}/bin/python" -m pip install --upgrade pip
    "${VENV_DIR}/bin/pip" install -e "${ROOT_DIR}/tau2-bench"
    "${VENV_DIR}/bin/pip" install -e "${ROOT_DIR}[dev,data]"
    install_source_path_file "${VENV_DIR}"
    ;;
  *)
    echo "usage: $0 {cpu-test|a800-qwen35}" >&2
    exit 2
    ;;
esac

echo "environment ready: ${VENV_DIR}"
