#!/usr/bin/env bash
# Canonical deployment. Source this file; all durable project artifacts live in code/.
export TAU3_ROOT=/root/autodl-fs/tau3-core
export TAU3_SHARED_ROOT="$TAU3_ROOT"
export CODE_ROOT="$TAU3_ROOT/code"
source "$TAU3_ROOT/environment/venvs/qwen35/bin/activate"
export TAU3_BASE_VENV="$TAU3_ROOT/environment/venvs/qwen35"
export TAU3_SIM_VENV="$TAU3_ROOT/environment/venvs/qwen38-sim"
export TAU3_SIM_PYTHON="$TAU3_SIM_VENV/bin/python"
export TAU3_FLA_OVERLAY="$TAU3_ROOT/environment/overlays/fla"
export PYTHONPATH="$CODE_ROOT:$CODE_ROOT/tau2-bench/src:$CODE_ROOT/verl:$TAU3_FLA_OVERLAY"
export TAU3_ENV_FILE="$CODE_ROOT/.env"
export TAU3_MODEL_ROOT="$CODE_ROOT/models"
export TAU3_DATA_ROOT="$CODE_ROOT/data"
export TAU3_TEST_TOKENIZERS="$TAU3_DATA_ROOT/tokenizers"
export TAU3_RUN_ROOT="$CODE_ROOT/results/runs"
export TAU3_CHECKPOINT_ROOT="$CODE_ROOT/checkpoints"
export TAU3_CACHE_ROOT="$CODE_ROOT/.cache"
export TAU3_SCRATCH_ROOT="$TAU3_CACHE_ROOT/runtime"
export TAU3_SIM_CACHE_ROOT="$TAU3_CACHE_ROOT/qwen38-sim"
export QWEN35_SIZE=4B
export QWEN35_MODEL_PATH="$TAU3_MODEL_ROOT/Qwen3.5-4B"
# RL profiles select their SFT checkpoint; do not override MODEL_PATH here.
export SFT_MODEL_NAME_OR_PATH="$QWEN35_MODEL_PATH"
export TAU3_USER_MODEL="$TAU3_MODEL_ROOT/Qwen3.8-27B-AWQ-INT4"
export TAU3_USER_SERVED_MODEL_NAME=Qwen/Qwen3.8-27B-AWQ-INT4
export TAU3_USER_BASE_URL=http://127.0.0.1:8100/v1
export TAU3_POLICY_CUDA_DEVICES=0,1,2,3
export POLICY_GPUS=4
export ROLLOUT_TP=1
export TAU3_USER_CUDA_DEVICES=4
export TAU3_USER_TP=1
export SFT_GPU=0
